### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by Mehdi1m** [CliffS/coinex.com#19]
I get the following errro during installation of this repository, I will be grateful for your feedback. 

```
<npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "coinex.com" under a package
npm ERR! also called "coinex.com". Did you name your project the same
npm ERR! as the dependency you're installing?
npm ERR! 
npm ERR! For more information, see:
npm ERR!     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shokati/.npm/_logs/2021-11-19T14_25_55_128Z-debug.log>
```

**Comment by CliffS** [comment]
@Mehdi1m It looks to me like you've created a project called coinex.com and you're trying to install this package into it. Try renaming your project, maybe?

**Comment by Mehdi1m** [comment]
Thank you very much for your helpful reply. After installation I get the following errors for each request,  I am new in NODE and I will be grateful for your feedback. 

The  filename is `new.js `


Request  1 
```
 coinex = require('coinex.com');

const API_KEY = "xxxx";
const SECRET  = "xxxx";
const coinex = new Coinex(API_KEY, SECRET);

coinex.placeMarketOrder(IOTAUSDT, sell, 3);
.then(response => console.log(response));
.catch(err => console.error(err.code, err.message);
```

Error 1 
```
/home/shokati/Desktop/new.js:8
.then(response => console.log(response));
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```
  Request 2  

```

  coinex = require('coinex.com');

const API_KEY = "xxxx";
const SECRET  = "xxxx";
const coinex = new Coinex(API_KEY, SECRET);

coinex.balance()
.then(response => console.log(response));
.catch(err => console.error(err.code, err.message);

```

Error 2 
```
/home/shokati/Desktop/new.js:9
.catch(err => console.error(err.code, err.message);
^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```

**Comment by CliffS** [comment]
You have semicolons at the end of your `.then()` statements.  Also I can't see where the variables `IOTAUSDT` and `sell` are set.

I'm really not here to teach javascript programming.  I'm closing this ticket.  If you have problems with the actual library, please feel free to open a fresh ticket.
